name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v3
      with:
        name: hospital-appointment-system
        path: target/*.jar

    - name: Create Release and Upload JAR
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
