name: Java CI Pipeline

on:
  push:
    branches: ["**"]  # Triggers on push to any branch
  pull_request:
    branches: ["main"]  # Triggers on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Use your project's Java version

    - name: Build and run tests with Maven
      run: mvn clean verify
